services:
  frontend:

    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile

    container_name: AppVIOL_frontend

    working_dir: /app

    volumes:
      - ./frontend:/app

    ports:
      - "5173:5173"

    stdin_open: true

    tty: true

    depends_on:
      - backend

    networks:
      - violapp_network
    
    command: npm run dev

  backend:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile

    container_name: AppVIOL_backend

    working_dir: /app

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    stdin_open: true

    tty: true

    networks:
      - violapp_network
    
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}


networks:
  violapp_network:
    driver: bridge
    external: true